### ISSUE TITLE
ReDoRecover 4.0.0 CAN DESTROY YOUR BACKUP’S

### ISSUE THREAD

**Issue by jtlpa** [redorescue/redorescue#126]
I make regular full system backups of my computers MBR, PARTITIONS (including the SWAP partition) to an external USB drive. 

ReDoRecover 4.0.0 will allow you to select the external USB drive and **over write the drive containing the backups**.

Expected behavior: ReDoRecover should not allow overwriting the drive containing the backups.

**Comment by zebradots** [comment]
This is true. Redo will do whatever you instruct it to do, including overwrite an entire drive. There are a number of use cases where this behavior is desired. **In addition to backups, there may be many other valuable files on a target drive, which is why Redo asks for confirmation before proceeding with any operation.**
