### ISSUE TITLE
Backup fails, complains NTFS partition is read only

### ISSUE THREAD

**Issue by DillFrescott** [redorescue/redorescue#29]
A fatal error occurs saying the destination NTFS HDD is read only. It's not read only. Clonezilla can write to it just fine. Please help!

**Comment by zebradots** [comment]
Thanks for sharing this report. It sounds as though either (a) the partition has been mounted read-only, or (b) filesystem permissions are preventing write access. We will need more details to help:

1. How is the drive connected? We assume that it is directly connected via SATA or USB.
2. Does this occur at the step titled **Creating backup image**, when the progress bar is shown? If so, please click the three dots on the right side of the screen below the progress bar to display the logs, then click **Copy to clipboard** and post the log (or at least any lines that seem relevant).
3. After the destination partition is selected, does Redo allow you to create a new folder to store the backup in?
4. Immediately after the destination partition is selected, and before you attempt the backup, are you able to open a file explorer (or run `ls -als /mnt/remote` in a terminal) to confirm the drive's contents are listed?
5. Just as with the step above, before you attempt a backup, please open a terminal and run `mount | grep remote` to provide us with the output. This will tell us if the partition is mounted read-only.

Sometimes partitions with filesystem inconsistencies are mounted read-only, and if these issues are corrected, the drive will mount read-write and writing files will work. One possible solution: Make sure the partition is not mounted (or simply reboot, to be safe). Use the Start menu to launch **Gparted**, choose the correct disk on the top right, and then right-click the NTFS partition to check its filesystem for errors. You will need to click **Apply** afterward to perform the check. If any problems are fixed, you can then attempt the backup again to see if the problem is fixed.

**Comment by DillFrescott** [comment]
No problem.

1. SATA

2. It won;t let me make a file in the file browser. It throws a fatal error when trying to write the backup image. I will have to reboot and run it again. I will reply in a little bit with the error log.

3. No

4. The contents are listed through the file manager, just they are read only. If this helps I also tried Rescuezilla, and it was able to write to the drive without any issues.

5. Ok. I will do this.

**Comment by zebradots** [comment]
Great, first let's get the output from step 5. If the output includes the read-only flag, we recommend trying the **Gparted** filesystem check mentioned above. Look forward to your response!

**Comment by DillFrescott** [comment]
I tried it again and it worked flawlessly. I could make the image and everything. So not sure what happened last time...

**Comment by DillFrescott** [comment]
Should I close the issue?

**Comment by zebradots** [comment]
If we had to guess, it could have been a filesystem inconsistency that was resolved after a reboot. Sure, we'll close the issue (or you can) and just re-open it later if you run into this more often. Thanks again for the report!

**Comment by DillFrescott** [comment]
No problem! Thank you for assisting me!

**Comment by DillFrescott** [comment]
Ok. It's doing it again. I tried rebooting and everything to no avail. Here are some pictures of the error.

https://ibb.co/album/FmSYrq

**Comment by zebradots** [comment]
@DillFrescott, thank you for the detailed information. You can also use the built-in browser to access GitHub and post the text output, so you don't have to use screenshots.

So we've gathered that the NTFS partition is mounting read-only, since `mount | grep remote` reports:

```
/dev/sda1 on /mnt/remote type fuseblk (ro,relatime,user_id=0,group_id=0,allow_other,blksize=4096
```

That `ro` part means the partition is being mounted in read-only mode. This is very likely because the filesystem contains an error. So to be safe, the partition is mounted read-only to prevent any more problems. What can cause this? We aren't entirely sure. Power loss, turning the power off instantly without a proper Windows shut down, or not [performing a full shutdown of Windows](https://blogs.technet.microsoft.com/askperf/2012/10/25/windows-8-windows-server-2012-faster-boot-process/) are all common causes. Hibernation can be a problem. Bad sectors (a failing drive) can result in filesystem inconsistencies. From what we can gather, it seems likely that the issue isn't caused by Redo, and unlikely that it could be fixed automatically, but Redo can try to present more information to the user if it's available.

To get more details, try entering the `mount` command manually in the terminal. Enter:
```
umount /dev/sda1; mkdir -p test; mount /dev/sda1 test
```
and check if any errors are output to the console.

Again, this issue probably has little to do with Redo, or Debian, or `ntfs-3g`... You may simply need to shutdown properly or run a filesystem check to correct any errors before it can safely be mounted read-write. We may not be able to determine the exact cause, but in the interim, you can search for the error message output from the `mount` command above to find possible solutions. One of the answers to [this forum question](https://askubuntu.com/questions/70281/why-does-my-ntfs-partition-mount-as-read-only) recommends running `ntfsfix /dev/sda1`. This might work, but always use caution with tools like this, as they could possibly make things worse. In a previous post, we recommended trying to use Gparted to run a filesystem check. The best way is to use the native Windows tools (assuming you have Windows on the machine), or better yet, find out the root cause and address it.

Please try the manual `mount` command, and if the output is marginally helpful, we may look into the best way to return that output immediately when a partition is mounted.

**Comment by DillFrescott** [comment]
Ok. Thanks for the info I've been very busy lately. You are absolutely right. Redo rescue makes it incredibly easy to switch operating systems and switch back so I was trying out Ubuntu and I believe it said something about an error on that drive under the disks utility.
