### ISSUE TITLE
Disk size comparison issue

### ISSUE THREAD

**Issue by Sadi58** [redorescue/redorescue#37]
Today I tried the new Redo Rescue 2.0 and encountered a strange problem while trying to clone my Kubuntu system to another disk: **an error message complaining that target disk is far smaller than the source disk**. It is true that the source disk total size is a lot larger than the target disk. However, the source partitions saved (sda5 and sda6) are identical in size to target partitions (sda1 and sda2) in the target disk, which contains only these 2 partitions in addition to a small swap partition. I didn't have such a problem in Clonezilla when saving and restoring partitions.
Fortunately I could complete the task by switching to the other option which enabled me to restore data on partitions sda5 and sda6 of the source disk to partitions sda1 and sda2 of the target disk.
If this is not a bug but how Redo Rescue works, I think it should be made clearer that the first option is only for disk to disk cloning, not partition to partition.

**Comment by zebradots** [comment]
Yes, this is exactly the way Redo was designed to operate.

The first option restores the partition table. If the partition table is pointing to partitions that do not exist or couldn't possibly fit on the drive, then something is horribly wrong. So the first option requires a drive equal in size (or larger) than the source drive.

The second option leaves the partition table intact, which permits you to do what you described without any problems, and without regard for the size of the drive itself (since the partition sizes are all that matter in that case).

When hovering your cursor over the help icon near these two options, this behavior should be made clear. If you can think of a better way to word this (both for advanced users and beginners alike), we are open to suggestions. Thank you for your input!

**Comment by Sadi58** [comment]
@zebradots Thanks! I actually thought of this as I was writing a "bug report". It seems my experience with Clonezilla might also have affected me so that I would expect the first option to be named something like "**Disk Recovery/Restore**", and the second "**Partition Recovery/Restore**", which might be clearer to all users IMHO.
The term "full system" sounds a bit ambiguous to me. As for the info tooltip, "Restores backup image even if the target is blank" doesn't help much either. Doesn't the second option work on empty target partition(s)? I guess it does. The following sentence kind of implies this operation is meant to affect the whole disk, but it doesn't seem enough as my confusion shows.
The term "data only" was apparently confusing for me, thinking it meant a simple operation of copying data files, excluding things like, for example, partition UUIDs, and whatever more I don't know. I think changing the name of this option as I've suggested might be enough but otherwise the "only writes data" in the info tooltip doesn't seem enough.

**Comment by zebradots** [comment]
Thanks for this valuable input @Sadi58!

Addressing terminology like this will always be a challenge because one's grandma, for example, likely has no clue what a "partition" is. At best, a beginner might understand what a "disk" is, and anyone can imagine there are "parts" of that disk, or that a restore may be _partial_, as opposed to _full_.

We want to resist getting too technical here, as some terms may immediately confuse the majority of users that we know make use of this utility on a regular basis. More features and more technical words lead to a more Clonezilla-like experience, which is precisely what Redo was created to fix.

We appreciate your input and will carefully revisit the wording of these options. We feel the two options titles should remain simple, so as not to intimidate users trying to just "restore the whole system." This is still within reach based on the current wording, whereas a "Disk Recovery/Restore" may not clearly convey that end result. We are not simply being pedantic: the current words were selected after much discussion due to confused users. We realize that not everyone will prefer the descriptions, no matter how they are worded, but we want to make them as broadly understandable by the majority of users as possible. One way to improve may be to ensure the tooltips contain proper terminology for more advanced users (or those who are willing to look up these terms for more clarity) so as to avoid ambiguity.

Your thoughts are welcome, and once again, thank you for your valuable input!

**Comment by Sadi58** [comment]
@zebradots Thanks a lot for the explanation, which I fully understand, and believe you'll find the best solution either by slightly improving the wording of the two option titles and/or expanding the information tooltips, possibly including the exact technical description as well.
