### ISSUE TITLE
Support exFAT

### ISSUE THREAD

**Issue by PROBLEMCHYLD** [redorescue/redorescue#45]
Can you add exFAT support?
Can you add a restart option instead of an Shutdown only option?
Can you add better compression? Clonezilla compresses about 2.5 GB smaller than redo.
Can you update Gparted?
Can you remove the notifications in the upper right corner?

**Comment by zebradots** [comment]
Thanks for the suggestions. Each is addressed below:

1. Added with https://github.com/redorescue/redorescue/commit/410727c0909474072559061f7d67892288e529b9
2. We considered this, but decided not to due to the fact `tint2` does not offer a shutdown menu. Until this is added, we're going to stick with one icon, plus forcing shutdown ensures the system is powered off and all writes are flushed before the media gets removed and the machine is powered back on. (If you don't like it, you can easily open a terminal and `reboot`!)
3. The compression level option `--fast` has been removed, which reverts to the default (level 6). This should be a good tradeoff between speed and image size. We don't want images to be too large, nor the backup speed to be too slow, and this is a fair compromise. This change was made in https://github.com/redorescue/redorescue/commit/94d417dd2f52e1c2f328e0e244cb8fa2a9ed7837.
4. This will happen with the next release, which is going to be based on Debian Buster.
5. No, we need these. But you can certainly edit `make`, remove the `libnotify-bin xfce4-notifyd` packages from the list, and run it to make your own custom ISO image.

Thanks again for the suggestions. Please create a separate issue for each feature request in the future so we can handle them properly.
