### ISSUE TITLE
Login prompt: Redorescue ask me login and password

### ISSUE THREAD

**Issue by erbavoglio** [redorescue/redorescue#62]
Hi, I have a system dual boot Win10+Ubuntu 20.04.
When i start redorescue by usb it's start but later initial screen i have screen black with 
redorescue login:

Can you help me to resolve?

Thanks

**Comment by pandlab** [comment]
Hi
login and password is available on https://github.com/redorescue/redorescue

have you had any errors? (you can use journalctl)

I had problems with devices - related to known debian problems.

**Comment by zebradots** [comment]
Hi @erbavoglio,

Have you tried running Debian 10 live on this machine? This is the base for Redo and if your hardware is supported by it then we need to dig a little deeper and find out why. However, if your hardware is not supported by Debian, there isn't much we can do other than recommend an older version (2.0 series, based on Debian 9) for now. Please see #60, as this is very likely due to your graphics adapter. What kind of GPU does your system have?

**Comment by zebradots** [comment]
See #60

**Comment by erbavoglio** [comment]
@zebradots Thank you for your answers, i have tested Debian 10 live and it's not work on my hardware the error during boot is in the file attached.
My notebook is Acer A315-42-R22P, it's provide with AMD Ryzen 7 and GPU Radeon Vega Graphics.
![20201218_130557](https://user-images.githubusercontent.com/75200453/102613779-6a732280-4133-11eb-8cd0-fbe45119fd46.jpg)

I hope you can early resolve this problem.

**Comment by zebradots** [comment]
Hi @erbavoglio, this is unfortunately where Debian 10 leaves us for now. Redo is not really a Linux distro but a backup tool, and we are not in the position of being able to maintain a full blown Linux distribution with bleeding edge kernel updates for the latest hardware. I believe your best bet would either be to use a non-UEFI (Redo 2.x) image or wait until Debian 11 is released and Redo can be based on that. Hopefully the newer kernel it provides will correct a lot of the errors users like you are seeing.

**Comment by vvpnet** [comment]
I have the same problem. Lenovo ThinkPad P14s Gen 1 AMD Laptop [P14s G1 20Y1001HRT]
